### ISSUE TITLE
ER: Simplify reporting of atomic writes

### ISSUE THREAD

**Issue by rgov** [zcutlip/prefsniff#1]
I think that the defaults system is doing atomic writes to the filesystem, which is polluting the output of prefsniff in directory mode. [Here's a version of the logic for atomic writes](https://github.com/apple/swift-corelibs-foundation/blob/c5357f39dd15ae858dc72d15bbabe5435376db70/Foundation/NSPathUtilities.swift#L656), basically you create a temporary file, write to it, and then move it over the original file:

Currently the output contains patterns like this:

```
# temporary file is created with open(filename + tmpsuffix, "w")
Detected change: [created] /Users/zach/Library/Preferences/com.apple.dock.plist.DnakVR2

# new file is a change to the directory listing
Detected change: [modified] /Users/zach/Library/Preferences/

# original file is deleted, which doesn't seem atomic to me ?
Detected change: [deleted] /Users/zach/Library/Preferences/com.apple.dock.plist

# write() is called, or perhaps close() flushes the kernel buffer to disk
Detected change: [modified] /Users/zach/Library/Preferences/com.apple.dock.plist.DnakVR2

# the temporary file is moved into the place of the original
Detected change: [moved] /Users/zach/Library/Preferences/com.apple.dock.plist.DnakVR2

# directory listing updates again because temporary file disappeared
Detected change: [modified] /Users/zach/Library/Preferences/
```

The proposed solution you gave was to omit everything that doesn't end with `.plist`, but I'm not sure it works---consider what the above log would look like if you did so, it would just say that the original `.plist` was deleted.

**Comment by zcutlip** [comment]
Yeah, not sure. I'm seeing a bunch of creation/deletions, but probably with more testing I'd see moves as well. At any rate this mode is just to give you a hint about what files are being messed with so you have an idea what specific file to watch. I think the deletion gives you that, even if you never see the creation of the new file?

I'll work on coming up with a better solution. Maybe a command line option to disable filters altogether.

**Comment by zcutlip** [comment]
Not sure this is a pressing issue. I think the current output, though noisy, gives sufficient information to infer which plist file to watch.

Closing for now, but open to considering proposed solutions to the issue
